;;;;This file was automatically generated by;;;;
;;;;major-mode-hooks-setup.el and shouldn't;;;;
;;;;need to be edited manually;;;;

(add-hook 'emacs-lisp-mode-hook (lambda () (load-file (concat yf/major-mode-hooks-dir "emacs-lisp-mode-file.el"))))
(add-hook 'text-mode-hook (lambda () (load-file (concat yf/major-mode-hooks-dir "text-mode-file.el"))))

;;end of major-mode-hooks.el
