;;;;;;;;;;Automatically generated by yf-edit-major-mode-hook;;;;;;;;;;;
(message "hello world! this is an elisp buffer!")
(make-local-variable 'popato-useage)
(setq 'popato-usage "General Kenobi")

;;'emacs-lisp-mode-hook.el ends here
