;;;;;;;;;;Automatically generated by yf-edit-major-mode-hook;;;;;;;;;;;

;; Automatic cider-jack in
(when (and (clojure-project-dir)
	   (not (seq-reduce (lambda (a b) (or a b))
			    (mapcar
			     (lambda (in) (equal (cl-search "*cider-repl" in) 0))
			     (projectile-project-buffer-names))
			    nil)))
  (cider-jack-in))

(general-define-key
 :keymaps 'clojure-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 :states '(normal insert emacs)
 "re" 'cider-eval-last-sexp
 "rE" (lambda () (cider-eval-last-sexp t))
 "rb" 'cider-eval-buffer
 "rd" 'cider-eval-defun-at-point
 "T" 'cider-test-run-project-tests
 "dd" 'cider-debug-defun-at-point)



;;clojure-mode.el ends here
