;;;;;;;;;;Automatically generated by auto-mode-files;;;;;;;;;;;

(general-define-key
 :keymap 'flycheck-mode-menu-map
 :non-normal-prefix "M-SPC"
 :states '(normal insert emacs)
 "M-s" 'flyspell-auto-correct-word)

;;flyspell-mode.el ends here
