;;;;;;;;;;Automatically generated by auto-mode-files;;;;;;;;;;;

(company-mode-on)
(smartparens-mode)
(rainbow-delimiters-mode-enable)

(general-define-key
 :keymaps 'latex-mode-map
 :non-normal-prefix "M-SPC"
 :states '(insert)
 "C-t" (lambda () (interactive) (insert "\texttt{}") (backward-char 1))
 "rB" 'racket-run-and-switch-to-repl
 "t" 'yf-run-raco-tests)
;;latex-mode.el ends here
