;;;;;;;;;;Automatically generated by auto-mode-files;;;;;;;;;;;

(defun yf-run-scheme-tests (file-to-test)
  (interactive (list (buffer-file-name)))
  "Automatically runs the tests in `file-to-test'-test.rkt
and complains about the failed cases"
  (let* ((test-file-name
	  (concat (file-name-directory file-to-test)
		  (file-name-nondirectory (file-name-sans-extension file-to-test))
		  "-test."
		  (file-name-extension file-to-test))))
    (message (or (shell-command-to-string (concat "racket " test-file-name)) "All tests passed"))
    ))

(general-define-key
 :keymaps 'scheme-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 :states '(normal insert emacs)
 "rs" 'geiser-eval-last-sexp
 "rS" (lambda () (cider-eval-last-sexp t))
 "r" nil
 "rb" 'geiser-eval-buffer
 "rB" 'geiser-eval-buffer-and-go
 "rd" 'geiser-eval-defun-at-point
 "rD" 'geiser-eval-defun-at-point-and-go
 "d" 'geiser-debug)

(turn-on-pretty-mode)

;;scheme-mode.el ends here
