;;;;;;;;;;Automatically generated by auto-mode-files;;;;;;;;;;;

(general-define-key
 :keymaps 'scheme-mode-map
 :prefix "SPC"
 :non-normal-prefix "M-SPC"
 :states '(normal insert emacs)
 "rs" 'geiser-eval-last-sexp
 "rS" (lambda () (cider-eval-last-sexp t))
 "r" nil
 "rb" 'geiser-eval-buffer
 "rB" 'geiser-eval-buffer-and-go
 "rd" 'geiser-eval-defun-at-point
 "rD" 'geiser-eval-defun-at-point-and-go
 "d" 'geiser-debug)

(turn-on-pretty-mode)

;;scheme-mode.el ends here
