;;;;;;;;;;Automatically generated by yf-edit-major-mode-hook;;;;;;;;;;;

(use-package latex-preview-pane
  :config
  (latex-preview-pane-enable))

(sp-local-pair 'LaTeX-mode "$" "$")
(sp-local-pair 'latex-mode "$" "$")

(evil-define-key 'insert 'latex-mode-map (kbd "C-m") (lambda () (interactive) (yas-expand-snippet (yas-lookup-snippet "math-mode"))))

(provide 'latex-mode-file)
